# Generated by Django 6.0.1 on 2026-02-02 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('app_label', models.CharField(blank=True, max_length=255)),
                ('permissions', models.JSONField(default=list)),
                ('risk_report', models.JSONField(default=list)),
                ('policy_issues', models.JSONField(default=list)),
                ('suspicious_services', models.JSONField(default=list)),
                ('verdict', models.CharField(choices=[('REJECTED', 'Rejected'), ('WARNING', 'Warning'), ('APPROVED', 'Approved')], max_length=20)),
                ('rejection_probability', models.FloatField(default=0.0)),
                ('confidence', models.CharField(default='LOW', max_length=10)),
                ('reasons', models.JSONField(default=list)),
                ('remediations', models.JSONField(default=list)),
                ('reviewer_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manifest_file', models.FileField(blank=True, null=True, upload_to='manifests/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
